"""empty message

Revision ID: 08e596fe4648
Revises: 53868e8de7b9
Create Date: 2018-07-09 19:45:12.639284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e596fe4648'
down_revision = '53868e8de7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'lambda_log_group_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('lambda_log_group_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
