"""empty message

Revision ID: 0a7e626686b8
Revises: a926537f63f4
Create Date: 2018-06-18 21:55:00.146605

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0a7e626686b8'
down_revision = 'a926537f63f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('root_nodes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('node_id', sa.Integer(), nullable=True),
                    sa.Column('is_root_node', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('root_nodes')
    # ### end Alembic commands ###
