"""empty message

Revision ID: 11427e27209a
Revises: 70637ca3e7dd
Create Date: 2018-06-15 14:54:13.392192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11427e27209a'
down_revision = '70637ca3e7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('node_utterance_node_utterance_worker_job_id_fkey', 'node_utterance', type_='foreignkey')
    op.drop_column('node_utterance', 'node_utterance_worker_job_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_utterance', sa.Column('node_utterance_worker_job_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('node_utterance_node_utterance_worker_job_id_fkey', 'node_utterance', 'node_utterance_worker_job', ['node_utterance_worker_job_id'], ['id'])
    # ### end Alembic commands ###
