"""empty message

Revision ID: 119ff6377bec
Revises: 23f30fdf1437
Create Date: 2018-07-31 01:09:37.417533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119ff6377bec'
down_revision = '23f30fdf1437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_utterance_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('rating_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=True),
    sa.Column('user_utterance_topic', sa.String(), nullable=True),
    sa.Column('user_utterance_intent', sa.String(), nullable=True),
    sa.Column('system_utterance_topic', sa.String(), nullable=True),
    sa.Column('system_utterance_intent', sa.String(), nullable=True),
    sa.Column('response_quality', sa.Integer(), nullable=True),
    sa.Column('is_coherent', sa.Boolean(), nullable=True),
    sa.Column('is_engaging', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['rating_id'], ['rating.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_utterance_row_conversation_id'), 'rating_utterance_row', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_rating_utterance_row_rating_id'), 'rating_utterance_row', ['rating_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_utterance_row_rating_id'), table_name='rating_utterance_row')
    op.drop_index(op.f('ix_rating_utterance_row_conversation_id'), table_name='rating_utterance_row')
    op.drop_table('rating_utterance_row')
    # ### end Alembic commands ###
