"""empty message

Revision ID: 1b362fc9fb47
Revises: 11427e27209a
Create Date: 2018-06-15 15:59:57.659976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b362fc9fb47'
down_revision = '11427e27209a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incoherent_node_utterance_worker_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('node_utterance_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.String(), nullable=True),
    sa.Column('hit_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['node_utterance_id'], ['node_utterance.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id', 'worker_id', 'job_id', 'node_utterance_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incoherent_node_utterance_worker_job')
    # ### end Alembic commands ###
