"""empty message

Revision ID: 218a70068d68
Revises: 275d6da3e436
Create Date: 2018-06-19 13:03:25.284463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218a70068d68'
down_revision = '275d6da3e436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('potential_node_merge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('left_node_id', sa.Integer(), nullable=True),
    sa.Column('right_node_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('potential_node_merge')
    # ### end Alembic commands ###
