"""empty message

Revision ID: 23f30fdf1437
Revises: 705eea13b39d
Create Date: 2018-07-28 12:49:45.998546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f30fdf1437'
down_revision = '705eea13b39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_conversation_conversation_id'), 'conversation', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_user_utterance'), 'conversation', ['user_utterance'], unique=False)
    op.create_index(op.f('ix_incoherent_node_utterance_worker_job_hit_id'), 'incoherent_node_utterance_worker_job', ['hit_id'], unique=False)
    op.create_index(op.f('ix_incoherent_node_utterance_worker_job_job_id'), 'incoherent_node_utterance_worker_job', ['job_id'], unique=False)
    op.create_index(op.f('ix_incoherent_node_utterance_worker_job_node_utterance_id'), 'incoherent_node_utterance_worker_job', ['node_utterance_id'], unique=False)
    op.create_index(op.f('ix_incoherent_node_utterance_worker_job_worker_id'), 'incoherent_node_utterance_worker_job', ['worker_id'], unique=False)
    op.create_index(op.f('ix_job_node_utterance_job_id'), 'job_node_utterance', ['job_id'], unique=False)
    op.create_index(op.f('ix_merging_left_node_id'), 'merging', ['left_node_id'], unique=False)
    op.create_index(op.f('ix_merging_right_node_id'), 'merging', ['right_node_id'], unique=False)
    op.create_index(op.f('ix_node_active'), 'node', ['active'], unique=False)
    op.create_index(op.f('ix_node_parent_id'), 'node', ['parent_id'], unique=False)
    op.create_index(op.f('ix_node_visited_count'), 'node', ['visited_count'], unique=False)
    op.create_index(op.f('ix_node_utterance_node_id'), 'node_utterance', ['node_id'], unique=False)
    op.create_index(op.f('ix_node_utterance_source'), 'node_utterance', ['source'], unique=False)
    op.create_index(op.f('ix_node_utterance_utterance_id'), 'node_utterance', ['utterance_id'], unique=False)
    op.create_index(op.f('ix_node_utterance_status_handled'), 'node_utterance_status', ['handled'], unique=False)
    op.create_index(op.f('ix_node_utterance_status_node_utterance_id'), 'node_utterance_status', ['node_utterance_id'], unique=False)
    op.create_index(op.f('ix_node_utterance_status_status'), 'node_utterance_status', ['status'], unique=False)
    op.create_index(op.f('ix_node_utterance_worker_job_hit_id'), 'node_utterance_worker_job', ['hit_id'], unique=False)
    op.create_index(op.f('ix_node_utterance_worker_job_job_id'), 'node_utterance_worker_job', ['job_id'], unique=False)
    op.create_index(op.f('ix_node_utterance_worker_job_node_utterance_id'), 'node_utterance_worker_job', ['node_utterance_id'], unique=False)
    op.create_index(op.f('ix_node_utterance_worker_job_worker_id'), 'node_utterance_worker_job', ['worker_id'], unique=False)
    op.create_index(op.f('ix_rating_conversation_id'), 'rating', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_utterance_amazon_anonymous'), 'utterance', ['amazon_anonymous'], unique=False)
    op.create_index(op.f('ix_utterance_utterance_text'), 'utterance', ['utterance_text'], unique=False)
    op.drop_column('utterance', 'topic')
    op.drop_column('utterance', 'raw_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utterance', sa.Column('raw_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('utterance', sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_utterance_utterance_text'), table_name='utterance')
    op.drop_index(op.f('ix_utterance_amazon_anonymous'), table_name='utterance')
    op.drop_index(op.f('ix_rating_conversation_id'), table_name='rating')
    op.drop_index(op.f('ix_node_utterance_worker_job_worker_id'), table_name='node_utterance_worker_job')
    op.drop_index(op.f('ix_node_utterance_worker_job_node_utterance_id'), table_name='node_utterance_worker_job')
    op.drop_index(op.f('ix_node_utterance_worker_job_job_id'), table_name='node_utterance_worker_job')
    op.drop_index(op.f('ix_node_utterance_worker_job_hit_id'), table_name='node_utterance_worker_job')
    op.drop_index(op.f('ix_node_utterance_status_status'), table_name='node_utterance_status')
    op.drop_index(op.f('ix_node_utterance_status_node_utterance_id'), table_name='node_utterance_status')
    op.drop_index(op.f('ix_node_utterance_status_handled'), table_name='node_utterance_status')
    op.drop_index(op.f('ix_node_utterance_utterance_id'), table_name='node_utterance')
    op.drop_index(op.f('ix_node_utterance_source'), table_name='node_utterance')
    op.drop_index(op.f('ix_node_utterance_node_id'), table_name='node_utterance')
    op.drop_index(op.f('ix_node_visited_count'), table_name='node')
    op.drop_index(op.f('ix_node_parent_id'), table_name='node')
    op.drop_index(op.f('ix_node_active'), table_name='node')
    op.drop_index(op.f('ix_merging_right_node_id'), table_name='merging')
    op.drop_index(op.f('ix_merging_left_node_id'), table_name='merging')
    op.drop_index(op.f('ix_job_node_utterance_job_id'), table_name='job_node_utterance')
    op.drop_index(op.f('ix_incoherent_node_utterance_worker_job_worker_id'), table_name='incoherent_node_utterance_worker_job')
    op.drop_index(op.f('ix_incoherent_node_utterance_worker_job_node_utterance_id'), table_name='incoherent_node_utterance_worker_job')
    op.drop_index(op.f('ix_incoherent_node_utterance_worker_job_job_id'), table_name='incoherent_node_utterance_worker_job')
    op.drop_index(op.f('ix_incoherent_node_utterance_worker_job_hit_id'), table_name='incoherent_node_utterance_worker_job')
    op.drop_index(op.f('ix_conversation_user_utterance'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_conversation_id'), table_name='conversation')
    # ### end Alembic commands ###
