"""empty message

Revision ID: 275d6da3e436
Revises: 0a7e626686b8
Create Date: 2018-06-18 22:00:47.617038

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '275d6da3e436'
down_revision = '0a7e626686b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('root_node',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('node_id', sa.Integer(), nullable=True),
                    sa.Column('is_root_node', sa.Boolean(), nullable=True),
                    sa.Column('utterance', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('root_nodes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('root_nodes',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('node_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('is_root_node', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='root_nodes_pkey')
                    )
    op.drop_table('root_node')
    # ### end Alembic commands ###
