"""empty message

Revision ID: 326da3e857b9
Revises: 09cdb6c0041b
Create Date: 2018-05-30 14:23:24.807051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326da3e857b9'
down_revision = '09cdb6c0041b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utterance', sa.Column('topic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utterance', 'topic')
    # ### end Alembic commands ###
