"""empty message

Revision ID: 41901edd6a9e
Revises: fc8874d7a59b
Create Date: 2018-06-20 14:08:00.392995

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '41901edd6a9e'
down_revision = 'fc8874d7a59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_utterance_status', sa.Column('handled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node_utterance_status', 'handled')
    # ### end Alembic commands ###
