"""empty message

Revision ID: 43bc58168aa7
Revises: bc4fb481e301
Create Date: 2018-08-08 13:20:58.624115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43bc58168aa7'
down_revision = 'bc4fb481e301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utterance', 'has_more_than_20_qualifaction')
    op.add_column('worker', sa.Column('has_more_than_20_qualifaction', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker', 'has_more_than_20_qualifaction')
    op.add_column('utterance', sa.Column('has_more_than_20_qualifaction', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
