"""empty message

Revision ID: 44fb705503d8
Revises: a6955b6e5aee
Create Date: 2018-08-08 11:33:21.228111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44fb705503d8'
down_revision = 'a6955b6e5aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('job_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'job_type')
    # ### end Alembic commands ###
