"""empty message

Revision ID: 53868e8de7b9
Revises: fb823ed23d5f
Create Date: 2018-07-09 19:33:09.944900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53868e8de7b9'
down_revision = 'fb823ed23d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('lambda_function_version', sa.String(), nullable=True))
    op.add_column('conversation', sa.Column('lambda_log_group_name', sa.String(), nullable=True))
    op.add_column('conversation', sa.Column('stage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'stage')
    op.drop_column('conversation', 'lambda_log_group_name')
    op.drop_column('conversation', 'lambda_function_version')
    # ### end Alembic commands ###
