"""empty message

Revision ID: 6d38d766cc97
Revises: ef5f2eec7c54
Create Date: 2018-06-16 02:22:18.200404

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6d38d766cc97'
down_revision = 'ef5f2eec7c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_utterance',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('text', sa.String(), nullable=True),
                    sa.Column('appropriate', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anonymous_utterance')
    # ### end Alembic commands ###
