"""empty message

Revision ID: 705eea13b39d
Revises: 08e596fe4648
Create Date: 2018-07-26 20:15:41.637528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705eea13b39d'
down_revision = '08e596fe4648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utterance', sa.Column('is_spellchecked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utterance', 'is_spellchecked')
    # ### end Alembic commands ###
