"""empty message

Revision ID: 70637ca3e7dd
Revises: 42ccd12a6320
Create Date: 2018-06-15 14:37:33.825328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70637ca3e7dd'
down_revision = '42ccd12a6320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_equivalence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_equivalence',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('left_node_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('right_node_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['left_node_id'], ['node.id'], name='node_equivalence_left_node_id_fkey'),
    sa.ForeignKeyConstraint(['right_node_id'], ['node.id'], name='node_equivalence_right_node_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='node_equivalence_pkey')
    )
    # ### end Alembic commands ###
