"""empty message

Revision ID: 804129b3e01d
Revises: eb9d09c336d4
Create Date: 2018-06-14 14:00:14.449371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804129b3e01d'
down_revision = 'eb9d09c336d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_utterance_worker_job', sa.Column('assignment_id', sa.String(), nullable=True))
    op.add_column('node_utterance_worker_job', sa.Column('hit_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node_utterance_worker_job', 'hit_id')
    op.drop_column('node_utterance_worker_job', 'assignment_id')
    # ### end Alembic commands ###
