"""empty message

Revision ID: 85fb7494e552
Revises: 119ff6377bec
Create Date: 2018-07-31 01:49:21.126555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fb7494e552'
down_revision = '119ff6377bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_utterance_row', sa.Column('file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating_utterance_row', 'file_name')
    # ### end Alembic commands ###
