"""empty message

Revision ID: 86123a64bb1f
Revises: ace94a5b0e96
Create Date: 2018-06-30 14:20:14.664399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86123a64bb1f'
down_revision = 'ace94a5b0e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utterance', sa.Column('amazon_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('utterance', 'spellchecked_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utterance', sa.Column('spellchecked_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('utterance', 'amazon_anonymous')
    # ### end Alembic commands ###
