"""empty message

Revision ID: 929c5272277b
Revises: ba1b103da99d
Create Date: 2018-08-02 17:51:54.513108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929c5272277b'
down_revision = 'ba1b103da99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('turn_error', sa.Integer(), nullable=True))
    op.drop_column('rating_utterance_row', 'turn_error')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_utterance_row', sa.Column('turn_error', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('rating', 'turn_error')
    # ### end Alembic commands ###
