"""empty message

Revision ID: a926537f63f4
Revises: eb393406400d
Create Date: 2018-06-18 20:28:33.162987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a926537f63f4'
down_revision = 'eb393406400d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'active')
    # ### end Alembic commands ###
