"""empty message

Revision ID: aa5cd0308e05
Revises: 218a70068d68
Create Date: 2018-06-19 23:19:02.594386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa5cd0308e05'
down_revision = '218a70068d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incoherent_node_utterance_worker_job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incoherent_node_utterance_worker_job',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('node_utterance_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assignment_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hit_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name='incoherent_node_utterance_worker_job_job_id_fkey'),
    sa.ForeignKeyConstraint(['node_utterance_id'], ['node_utterance.id'], name='incoherent_node_utterance_worker_job_node_utterance_id_fkey'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], name='incoherent_node_utterance_worker_job_worker_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'worker_id', 'job_id', 'node_utterance_id', name='incoherent_node_utterance_worker_job_pkey')
    )
    # ### end Alembic commands ###
