"""empty message

Revision ID: ace94a5b0e96
Revises: 7107a7f39d39
Create Date: 2018-06-27 13:03:30.172542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace94a5b0e96'
down_revision = '7107a7f39d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('feedback', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating', 'feedback')
    # ### end Alembic commands ###
