"""empty message

Revision ID: b824c68fa114
Revises: 929c5272277b
Create Date: 2018-08-03 17:30:18.202634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b824c68fa114'
down_revision = '929c5272277b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('graphsearch_matched_utterance_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'graphsearch_matched_utterance_id')
    # ### end Alembic commands ###
