"""empty message

Revision ID: ba1b103da99d
Revises: fdd473c926b6
Create Date: 2018-08-02 00:12:18.753624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1b103da99d'
down_revision = 'fdd473c926b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('transformed_user_utterance', sa.String(), nullable=True))
    op.create_index(op.f('ix_conversation_transformed_user_utterance'), 'conversation', ['transformed_user_utterance'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_transformed_user_utterance'), table_name='conversation')
    op.drop_column('conversation', 'transformed_user_utterance')
    # ### end Alembic commands ###
