"""empty message

Revision ID: d61ac139ee25
Revises: 1b362fc9fb47
Create Date: 2018-06-15 17:38:38.206948

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd61ac139ee25'
down_revision = '1b362fc9fb47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('named_enteties', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'named_enteties')
    # ### end Alembic commands ###
