"""empty message

Revision ID: e2f994d7d500
Revises: 77e3a32872ee
Create Date: 2018-05-17 01:21:46.075532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f994d7d500'
down_revision = '77e3a32872ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('merging_right_node_id_fkey', 'merging', type_='foreignkey')
    op.drop_constraint('merging_left_node_id_fkey', 'merging', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('merging_left_node_id_fkey', 'merging', 'node', ['left_node_id'], ['id'])
    op.create_foreign_key('merging_right_node_id_fkey', 'merging', 'node', ['right_node_id'], ['id'])
    # ### end Alembic commands ###
