"""empty message

Revision ID: e3ddf29d7607
Revises: d8802c8bb913
Create Date: 2018-07-31 15:03:17.038397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ddf29d7607'
down_revision = 'd8802c8bb913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_node_utterance', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_node_utterance', 'position')
    # ### end Alembic commands ###
