"""empty message

Revision ID: eb393406400d
Revises: 52082b30c959
Create Date: 2018-06-18 17:20:26.236561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb393406400d'
down_revision = '52082b30c959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('species', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'species')
    # ### end Alembic commands ###
