"""empty message

Revision ID: eb9d09c336d4
Revises: 326da3e857b9
Create Date: 2018-05-30 18:05:50.354047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9d09c336d4'
down_revision = '326da3e857b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('node_utterance_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversation', 'node_utterance', ['node_utterance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.drop_column('conversation', 'node_utterance_id')
    # ### end Alembic commands ###
