"""empty message

Revision ID: fb823ed23d5f
Revises: 86123a64bb1f
Create Date: 2018-06-30 15:39:15.624899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb823ed23d5f'
down_revision = '86123a64bb1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utterance', sa.Column('raw_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utterance', 'raw_text')
    # ### end Alembic commands ###
